
[font]
size = 12.5

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift"

# [[keyboard.bindings]]
# key = "T"
# mods = "Control"
#
# [keyboard.bindings.command]
# program = "/home/jona/.config/alacritty/themeswitch.sh"

[[keyboard.bindings]]
key = "Up"
mods = "Shift"

[keyboard.bindings.command]
program = "/home/jona/.config/alacritty/opacity.py"
args = ["0.01"]

[[keyboard.bindings]]
key = "Down"
mods = "Shift"

[keyboard.bindings.command]
program = "/home/jona/.config/alacritty/opacity.py"
args = ["-0.01"]

[[keyboard.bindings]]
key = "Right"
mods = "Shift"

[keyboard.bindings.command]
program = "/home/jona/.config/alacritty/opacity.py"
args = ["0.05"]

[[keyboard.bindings]]
key = "Left"
mods = "Shift"

[keyboard.bindings.command]
program = "/home/jona/.config/alacritty/opacity.py"
args = ["-0.05"]

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[general]
import = [
"/home/jona/.config/alacritty/theme.toml",
"/home/jona/.config/alacritty/opacity.toml"
]
